name: The Way Rider
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.50812
title: "On Life's Rails"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e3de'
    - '#3d3f3e'
    - '#6c8477'
    - '#a8bbb8'
    - '#73a767'
  brandStrength: 0.9843403084669262
  lightness: 0.4892694989684969
  saturation: 0.5891630577389151
  rhythmicContrast: 0.6372064284514636
purpose: []
